### ISSUE TITLE
Unable to download xlsx even with new version of plugin

### ISSUE THREAD

**Issue by stephhend** [glebovpavel/IR_to_MSExcel#60] opened 2019-04-30 22:01 UTC
Hi,

I installed the latest version https://github.com/glebovpavel/IR_to_MSExcel/archive/master.zip but I am still receiving the following error.

Can you help?

Error in PLSQL code raised during plug-in processing.

Contact your application administrator.
Technical Info (only visible for developers)

is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-06502: PL/SQL: numeric or value error: character to number conversion error ORA-06512: at "APEX_MA.IR_TO_XLSX", line 1270 ORA-06512: at "APEX_MA.IR_TO_XLSX", line 1289 ORA-06512: at "APEX_MA.IR_TO_XLSX", line 1762 ORA-06512: at "APEX_MA.IR_TO_XLSX", line 1929 ORA-06512: at "APEX_MA.IR_TO_XLSX", line 2099 ORA-06512: at "APEX_MA.IR_TO_MSEXCEL", line 306
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 1717688679702666513
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:

ORA-06512: at "APEX_MA.IR_TO_MSEXCEL", line 336
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SYS_SQL", line 2107
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190100", line 599
ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 2486
ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 1500
ORA-06512: at "APEX_190100.WWV_FLOW_PLUGIN", line 1383

error_statement:

begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

Thanks!
Stephanie

**Comment by stephhend** [comment] 2019-04-30 22:02
Hi,

I installed the latest version https://github.com/glebovpavel/IR_to_MSExcel/archive/master.zip but I am still receiving the following error.

Can you help?

Error in PLSQL code raised during plug-in processing.

Contact your application administrator.
Technical Info (only visible for developers)

is_internal_error: true
apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
ora_sqlcode: -20001
ora_sqlerrm: ORA-20001: ORA-06502: PL/SQL: numeric or value error: character to number conversion error ORA-06512: at "APEX_MA.IR_TO_XLSX", line 1270 ORA-06512: at "APEX_MA.IR_TO_XLSX", line 1289 ORA-06512: at "APEX_MA.IR_TO_XLSX", line 1762 ORA-06512: at "APEX_MA.IR_TO_XLSX", line 1929 ORA-06512: at "APEX_MA.IR_TO_XLSX", line 2099 ORA-06512: at "APEX_MA.IR_TO_MSEXCEL", line 306
component.type: APEX_APPLICATION_PAGE_DA_ACTS
component.id: 1717688679702666513
component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
error_backtrace:

ORA-06512: at "APEX_MA.IR_TO_MSEXCEL", line 336
ORA-06512: at line 4
ORA-06512: at "SYS.DBMS_SYS_SQL", line 2107
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190100", line 599
ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 2486
ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 1500
ORA-06512: at "APEX_190100.WWV_FLOW_PLUGIN", line 1383

error_statement:

begin declare

begin
wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
end;

Thanks!
Stephanie

**Comment by stephhend** [comment] 2019-05-06 21:56
I figured out I had an aggregate sum on one column that was causing the error.

**Comment by glebovpavel** [comment] 2019-05-07 09:22
Hi Stephanie,
Thank you very much for posting the reason of the error. It's very rare to be so courteous!
Your short message will help another user (i know at least one user have the same problem right now).

Regards,
Pavel

**Comment by stephhend** [comment] 2019-05-07 15:46
Hi,

 

By chance you would know a solution to allow that aggregate sum on my xlsx download? I really need to have the downloaded report to look like that:

 



 

But right now because of the Aggregate sum of column “# Of Agreements”, the plug in result in error.

 

Or maybe do you know of a different plug in that will allow me to have this format?

 

 

-- 
Regards,

http://www.oracle.com/
Stephanie Hendrick | M&A Integration Lead
Phone: HYPERLINK "tel:+1%209163155025"+1 9163155025 | Fax: HYPERLINK "fax:+1%209163155025"+1 9163155025 
Royalty Reporting and Contract Compliance
Oracle Global Controller Organization
1001 Sunset Blvd | Rocklin, CA 95765 

http://www.oracle.com/commitment

Oracle is committed to developing practices and products that help protect the environment

HYPERLINK "https://oradocs-corp.sites.us2.oraclecloud.com/authsite/rrcc-global/"Royalty Reporting and Contract Compliance

**Comment by glebovpavel** [comment] 2019-05-09 15:24
Hi,
looks like you are using Pl/SQL compiler optimization level >=3  - at result i get wron linen numbers by errors listed abowe. For example,  
IR_TO_MSEXCEL", line 306 is
v_affected_region_id apex_application_page_da_acts.affected_region_id%type;
this code can't raise exception. 

http://stevenfeuersteinonplsql.blogspot.com/2017/01/confused-by-your-error-backtrace-check.html

It is possible to compile the packages with optimization level = 2 , because right now it is impossible to find the reason of the error because of wrong line numbers.

P.S. I was trying to play with  aggregate functions on apex.oracle.com (include null values etc) but can#t reproduce an error.

P.S.2 Could you try to download CSV? Do you use computations?

**Comment by glebovpavel** [comment] 2019-05-24 12:20
Hallo Christine,


Unfortunately i still can't reproduce this error on my notebook or on apex.oracle.com.
I will be very grateful to you, if you can reproduce this error  on any dummy sample application on apex.oracle.com.

Anyway i will switch to the build-in apex logging in the next release - that can help to cach the error.

Regards,
Pavel

**Comment by stephhend** [comment] 2019-05-31 08:56
Hi,

 

I am not sure how to reproduce an error in a dummy application. I am pretty novice with APEX and tough myself everything I know which is pretty limited.

 

Is there another plugin what would allow to have computed/aggregated column?

 

 

-- 
Regards,

http://www.oracle.com/
Stephanie Hendrick | M&A Integration Lead
Phone: HYPERLINK "tel:+1%209163155025"+1 9163155025 | Fax: HYPERLINK "fax:+1%209163155025"+1 9163155025 
Royalty Reporting and Contract Compliance
Oracle Global Controller Organization
1001 Sunset Blvd | Rocklin, CA 95765 

http://www.oracle.com/commitment

Oracle is committed to developing practices and products that help protect the environment

HYPERLINK "https://oradocs-corp.sites.us2.oraclecloud.com/authsite/rrcc-global/"Royalty Reporting and Contract Compliance

**Comment by dennyssistema** [comment] 2019-06-19 19:39
I'm going through the same problem

**Comment by glebovpavel** [comment] 2020-01-22 21:16
Probably fixed in newest version 3.2. Anyway there are new logging feature to collect more data for detecting errors.

**Comment by glebovpavel** [comment] 2020-01-27 15:28
After some findings fixed in 3.24

**Closed by glebovpavel** 2020-01-27 15:28 UTC
Labels: probably fixed
