### ISSUE TITLE
Invalid report totals (sum aggregation)  in interactive report

### ISSUE THREAD

**Issue by Johan1959** [glebovpavel/IR_to_MSExcel#69] opened 2019-11-28 07:05 UTC
When an interactive report with totals (sum aggregation) has hidden columns that also include a total then the totals that appear in the excel file are incorrect. It seems the total from a hidden column is added to the excel.

A bypass is to remove the total (sum calculation) from the hidden column.

[DemoBAQuote1 (10).xlsx](https://github.com/glebovpavel/IR_to_MSExcel/files/3900265/DemoBAQuote1.10.xlsx)

**Comment by glebovpavel** [comment] 2020-01-22 21:12
Could you try the last version: 3.21. Probably is related to #70

**Comment by jporrata1** [comment] 2020-01-22 21:40
Hi Pavel

Where can I download it?

Which files do I need to import to the application?   All files or just one?

Thanks a lot for your help!

Javier

**Comment by mrpele** [comment] 2020-01-23 05:35
Hi Pavel,
After fixed issue #70, sum aggregations are incorrect.. Before that, if was ok for me.
Tested on Apex 19.2
Thanks.
Miraç

**Comment by glebovpavel** [comment] 2020-01-23 23:10
Fixed in 3.21

**Comment by mrpele** [comment] 2020-01-24 05:49
3.22 doesnt fixed this issue for me. Here is the screenshots;
![Hata1](https://user-images.githubusercontent.com/43929111/73047322-6c325880-3e86-11ea-9d63-29704877ef7e.png)
![Hata](https://user-images.githubusercontent.com/43929111/73047331-72c0d000-3e86-11ea-8a0d-aee8aec9feae.png)

**Comment by glebovpavel** [comment] 2020-01-25 21:18
@mrpele Could you reproduce this bug  on https://apex.oracle.com/pls/apex/f?p=35446:1 
? 
I was trying but 3.22 works correct for me.

**Comment by mrpele** [comment] 2020-01-26 07:59
I think i found the bug. It is caused by the hidden item/s. If ir doesnt have any hidden item (hidden item meaning is type of the item, not -undisplayed column) then it works like charm. But if ir has one hidden item, then just one aggregation is true, others are wrong. If ir has more then one hidden item then all aggregations are wrong.
![Adsız](https://user-images.githubusercontent.com/43929111/73132315-97ee4380-402a-11ea-8172-fe6a5d725be1.png)
I am looking forward for a solution.. 
Thanks.

**Comment by glebovpavel** [comment] 2020-01-26 23:28
@mrpele  Thank you for detailed description!!! I think now this bug should be fixed in 3.24

**Comment by mrpele** [comment] 2020-01-27 07:06
It seems ok..
Thanks Pavel.
Tested on Apex 19.2

**Closed** 2020-01-27 15:27 UTC
Labels: bug, probably fixed
