### ISSUE TITLE
highlight bug - plugin v2.20, Apex 5.1.2

### ISSUE THREAD

**Issue by damirko28** [glebovpavel/IR_to_MSExcel#29] opened 2017-12-05 10:34 UTC
Unfortunately, I'm coming back with a new one  bug  (on Apex 5.1.2):

**highlight** 

After start export, error message:

Error in PLSQL code raised during plug-in processing.

ORA-20001: ORA-01007: variable not in select list ORA-06512: at "SYS.DBMS_SQL", line 1589 ORA-06512: at "GSP.IR_TO_XLSX", line 1642 ORA-06512: at "GSP.IR_TO_XLSX", line 1848 ORA-06512: at "GSP.IR_TO_XLSX", line 2018 ORA-06512: at "GSP.IR_TO_MSEXCEL", line 157
Technical Info (only visible for developers)

    is_internal_error: true
    apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
    ora_sqlcode: -20001
    ora_sqlerrm: ORA-20001: ORA-01007: variable not in select list ORA-06512: at "SYS.DBMS_SQL", line 1589 ORA-06512: at "GSP.IR_TO_XLSX", line 1642 ORA-06512: at "GSP.IR_TO_XLSX", line 1848 ORA-06512: at "GSP.IR_TO_XLSX", line 2018 ORA-06512: at "GSP.IR_TO_MSEXCEL", line 157
    component.type: APEX_APPLICATION_PAGE_DA_ACTS
    component.id: 26318981105645610
    component.name: PLUGIN_AT.FRT.GPV_IR_TO_MSEXCEL
    error_backtrace:

    ORA-06512: at "GSP.IR_TO_MSEXCEL", line 178
    ORA-06512: at line 4
    ORA-06512: at "SYS.DBMS_SQL", line 1707
    ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 1880
    ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 1895
    ORA-06512: at "APEX_050100.WWV_FLOW_DYNAMIC_EXEC", line 936
    ORA-06512: at "APEX_050100.WWV_FLOW_PLUGIN", line 1330

    error_statement:

    begin declare

    begin
    wwv_flow_plugin_api.g_dynamic_action_ajax_result := IR_TO_MSEXCEL.ajax (p_dynamic_action => wwv_flow_plugin_api.g_dynamic_action,p_plugin => wwv_flow_plugin_api.g_plugin );end;
    end;

**Comment by glebovpavel** [comment] 2017-12-13 14:20
Hi Damir,

Unfortunately i can not reproduce this error. Can you attach an debug.txt for detailed analysis?
How to get this file described on the bottom of page 3 Instructions.pdf

Regards,
Pavel

**Comment by damirko28** [comment] 2017-12-13 15:31
Hi Pavel,

We are talking about Apex 5.1.2.
[issue#29.docx](https://github.com/glebovpavel/IR_to_MSExcel/files/1556001/issue.29.docx)


**CASE 1:**
I get error when I try to export IR (with highlight conditions) immediately after registering to Apex application. 

**CASE 2:**
If I make export without highlight conditions, then in the next step, export with the highlight condition is successfully executed.

Regards,
Damir

**Comment by glebovpavel** [comment] 2018-01-08 15:14
Hi Damir,

thank you for detailed description, but i still can't reproduce this error.
Could you give me a debug.txt?

Regards,
Pavel

**Comment by glebovpavel** [comment] 2018-05-08 10:10
Should be already fixed in v 3.13

**Closed by glebovpavel** 2018-05-08 10:10 UTC
Labels: bug, probably fixed
